version: '3.3'

services:
  spring:
    image: openjdk:17-alpine
    volumes:
      - ./build/libs:/app
    command: sh -c "java -jar /app/drinkingLibrary-0.0.1-SNAPSHOT.jar"

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:13
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5430:5432"

# docker-compose -f docker-compose.yml -p <<원하는 이름>> up